/****** Object:  Schema [PICKUP_TO_DELIVERY]    Script Date: 28.04.2022 14:54:25 ******/
CREATE SCHEMA [PICKUP_TO_DELIVERY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[ADDITIONAL_STATUS_CODES]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[ADDITIONAL_STATUS_CODES](
	[ASC_ID] [bigint] NULL,
	[CTE_ID] [bigint] NULL,
	[ADDITIONAL_STATUS_CODE_TYPE] [varchar](255) NULL,
	[ADDITIONAL_STATUS_CODE_VALUE] [varchar](255) NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[CANONICAL_TRACK_EVENT]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[CANONICAL_TRACK_EVENT](
	[CTE_ID] [bigint] NULL,
	[EVENT_ID] [varchar](255) NULL,
	[CREATION_TIMESTAMP] [datetime2](7) NULL,
	[HASH_VALUE] [varchar](255) NULL,
	[PRIMARY_CRITERIA] [varchar](255) NULL,
	[SECONDARY_CRITERIA] [varchar](255) NULL,
	[PALS_STATUS] [varchar](255) NULL,
	[FAKE_EVENT_FLAG] [int] NULL,
	[KIND_OF_EVENT_ZINS] [varchar](255) NULL,
	[KIND_OF_EVENT_SOLLWEG] [varchar](255) NULL,
	[SOLLWEG_EXCEPTION] [varchar](255) NULL,
	[DPAG_BARCODE] [varchar](255) NULL,
	[PRODUCTION_FLAG] [int] NULL,
	[READING_POST_NUMBER_REQUESTED] [int] NULL,
	[IS_OBSERVATION_FLAG] [int] NULL,
	[ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[PARENT_CONTAINER_TYPE] [varchar](255) NULL,
	[PARENT_CONTAINER_IDENTIFIER_TYPE] [varchar](255) NULL,
	[PARENT_CONTAINER_IDENTIFIER_VALUE] [varchar](255) NULL,
	[PARENT_ADDITIONAL_CONTAINER_IDENTIFIER_TYPE] [varchar](255) NULL,
	[PARENT_ADDITIONAL_CONTAINER_IDENTIFIER_VALUE] [varchar](255) NULL,
	[PARENT_CONTAINER_TIMESTAMP] [varchar](255) NULL,
	[EVENT_TYPE] [varchar](255) NULL,
	[MESSAGE_UUID] [bigint] NULL,
	[MESSAGE_SENDER] [varchar](255) NULL,
	[MESSAGE_RECIPIENT] [varchar](255) NULL,
	[MESSAGE_CREATION_TS] [datetime2](7) NULL,
	[MESSAGE_IS_TEST_FLAG] [int] NULL,
	[MESSAGE_ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[PMES_SEQUENCE_NUMBER] [float] NULL,
	[TRIGGERING_MESSAGE_UUID] [bigint] NULL,
	[TRIGGERING_MESSAGE_SENDER] [varchar](255) NULL,
	[TRIGGERING_MESSAGE_RECIPIENT] [varchar](255) NULL,
	[TRIGGERING_MESSAGE_CREATION_TS] [datetime2](7) NULL,
	[TRIGGERING_MESSAGE_IS_TEST_FLAG] [int] NULL,
	[DSTID] [int] NULL,
	[DATA_SOURCE_NAME] [varchar](255) NULL,
	[DATA_SOURCE_VERSION] [varchar](255) NULL,
	[DETAIL_SOURCE_INFORMATION] [varchar](max) NULL,
	[TARGET_TYPE_SOURCE] [varchar](255) NULL,
	[DPAG_BARCODE_SOURCE] [varchar](255) NULL,
	[DANGEROUS_GOODS_SOURCE] [varchar](255) NULL,
	[IDENTIFIER_SOURCE_1] [varchar](255) NULL,
	[IDENTIFIER_SOURCE_2] [varchar](255) NULL,
	[IDENTIFIER_SOURCE_3] [varchar](255) NULL,
	[IDENTIFIER_SOURCE_4] [varchar](255) NULL,
	[IDENTIFIER_SOURCE_5] [varchar](255) NULL,
	[ROUTING_INFORMATION_ZIP_SOURCE] [varchar](255) NULL,
	[ROUTING_INFORMATION_STREET_CODE_SOURCE] [varchar](255) NULL,
	[ROUTING_INFORMATION_HOUSE_NUMBER_SOURCE] [varchar](255) NULL,
	[ROUTING_INFORMATION_PRODUCT_CODE_SOURCE] [varchar](255) NULL,
	[ACTUAL_WEIGHT_SOURCE] [varchar](255) NULL,
	[ACTUAL_LENGTH_SOURCE] [varchar](255) NULL,
	[ACTUAL_WIDTH_SOURCE] [varchar](255) NULL,
	[ACTUAL_HEIGHT_SOURCE] [varchar](255) NULL,
	[ACTUAL_VOLUME_SOURCE] [varchar](255) NULL,
	[POST_NUMBER_SOURCE] [varchar](255) NULL,
	[COUNTRY_CODE_SOURCE] [varchar](255) NULL,
	[PRODUCT_KEY_SOURCE] [varchar](255) NULL,
	[WEIGHT_ALIBI_ID] [varchar](255) NULL,
	[WEIGHT_LEGAL_CODE] [varchar](255) NULL,
	[WEIGHT_ERROR_CODE] [varchar](255) NULL,
	[VOLUME_ALIBI_ID] [varchar](255) NULL,
	[VOLUME_LEGAL_CODE] [varchar](255) NULL,
	[VOLUME_ERROR_CODE] [varchar](255) NULL,
	[EKP_SOURCE] [varchar](255) NULL,
	[SOLLWEG_REASONCODE] [varchar](255) NULL,
	[VOLUME_DEVICE_ID] [varchar](255) NULL,
	[WEIGHT_DEVICE_ID] [varchar](255) NULL,
	[DATA_SOURCE_SW_TYPE] [varchar](255) NULL,
	[DATA_SOURCE_SW_NAME] [varchar](255) NULL,
	[DATA_SOURCE_SW_VERSION] [varchar](255) NULL,
	[MESSAGE_FORMAT_TYPE] [varchar](255) NULL,
	[MESSAGE_FORMAT_NAME] [varchar](255) NULL,
	[MESSAGE_FORMAT_VERSION] [varchar](255) NULL,
	[DANGEROUS_GOODS_CODE] [varchar](255) NULL,
	[DISTRIBUTION_PRODUCT_CODE] [int] NULL,
	[PRODUCT_CODE] [char](1) NULL,
	[HANDLING_CODE] [int] NULL,
	[ACTUAL_WEIGHT] [float] NULL,
	[ACTUAL_WEIGHT_UNIT] [varchar](255) NULL,
	[ACTUAL_WIDTH] [float] NULL,
	[ACTUAL_WIDTH_UNIT] [varchar](255) NULL,
	[ACTUAL_HEIGHT] [float] NULL,
	[ACTUAL_HEIGHT_UNIT] [varchar](255) NULL,
	[ACTUAL_LENGTH] [float] NULL,
	[ACTUAL_LENGTH_UNIT] [varchar](255) NULL,
	[ACTUAL_VOLUME] [float] NULL,
	[ACTUAL_VOLUME_UNIT] [varchar](255) NULL,
	[TRANSPORTATION_RECEIPT_ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[ALTERNATIVE_TARGET_HUB_NUMBER] [varchar](255) NULL,
	[ALTERNATIVE_TARGET_NAME] [varchar](255) NULL,
	[ALTERNATIVE_TARGET_ROUTING_REGION] [varchar](255) NULL,
	[ALTERNATIVE_TARGET_LOCATION] [varchar](255) NULL,
	[ALTERNATIVE_TARGET_CODE_NUMBER] [varchar](255) NULL,
	[ALTERNATIVE_TARGET_PROCESS_CODE] [varchar](255) NULL,
	[NEXT_TARGET_NAME] [varchar](255) NULL,
	[NEXT_TARGET_ROUTING_REGION] [varchar](255) NULL,
	[NEXT_TARGET_LOCATION] [varchar](255) NULL,
	[NEXT_TARGET_CODE_NUMBER] [varchar](255) NULL,
	[NEXT_TARGET_PROCESS_CODE] [varchar](255) NULL,
	[NEXT_TARGET_HUB_NUMBER] [varchar](255) NULL,
	[NEXT_TARGET_DELIVERY_BASE_NUMBER] [varchar](255) NULL,
	[NEXT_TARGET_DELIVERY_DISTRICT_NUMBER] [varchar](255) NULL,
	[NEXT_TARGET_DELIVERY_SECTION_NUMBER] [varchar](255) NULL,
	[LOGICAL_TARGET] [varchar](255) NULL,
	[LOGICAL_TARGET_DESCRIPTION] [varchar](255) NULL,
	[SORTING_TARGET_TYPE] [varchar](255) NULL,
	[SORTING_USED_COMPUTED_ROUTE] [varchar](255) NULL,
	[MAPPED_DESTINATION_ID] [varchar](255) NULL,
	[DROPPING_POINT_AN] [varchar](255) NULL,
	[INFEED_TYPE] [varchar](255) NULL,
	[INFEED_CODE] [varchar](255) NULL,
	[DIRECT_TRANSPORT_FLAG] [int] NULL,
	[CONTAINER_IDENTIFIER_TYPE] [varchar](255) NULL,
	[CONTAINER_IDENTIFIER_VALUE] [varchar](255) NULL,
	[HUB_TYPE] [varchar](255) NULL,
	[DESTINATION_ID] [varchar](255) NULL,
	[TARGET_TYPE] [varchar](255) NULL,
	[SCAN_POINT] [varchar](255) NULL,
	[DROPPING_POINT] [varchar](255) NULL,
	[EAN_PRODUCT_CODE] [varchar](max) NULL,
	[CREATION_LOCATION_ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[PRODUCTION_LOCATION_NAME] [varchar](255) NULL,
	[PRODUCTION_LOCATION_ROUTING_REGION] [varchar](255) NULL,
	[PRODUCTION_LOCATION_LOCATION] [varchar](255) NULL,
	[PRODUCTION_LOCATION_CODE_NUMBER] [varchar](255) NULL,
	[PRODUCTION_LOCATION_PROCESS_CODE] [varchar](255) NULL,
	[CREATION_LOCATION_ADDRESS_TYPE] [varchar](255) NULL,
	[CREATION_LOCATION_ADDRESS_STREET] [varchar](255) NULL,
	[CREATION_LOCATION_ADDRESS_HOUSE_NUMBER] [varchar](255) NULL,
	[CREATION_LOCATION_ADDRESS_ZIP] [varchar](255) NULL,
	[CREATION_LOCATION_ADDRESS_CITY] [varchar](255) NULL,
	[CREATION_LOCATION_COUNTRY_CODE] [varchar](255) NULL,
	[CREATION_LOCATION_PRODUCTION_FACILITY_NUMBER_TYPE] [varchar](255) NULL,
	[CREATION_LOCATION_PRODUCTION_FACILITY_NUMBER_VALUE] [varchar](255) NULL,
	[CREATION_LOCATION_PRODUCTION_FACILITY_TYPE] [varchar](255) NULL,
	[PHYSICAL_PRODUCTION_LOCATION_NAME] [varchar](255) NULL,
	[CNT_ID] [bigint] NULL,
	[DELIVERY_NET] [varchar](255) NULL,
	[DELIVERY_TOUR_COMPOUND_COUNT_SECTION] [varchar](255) NULL,
	[DELIVERY_TOUR_COMPOUND_POSITION] [varchar](255) NULL,
	[DELIVERY_TOUR_COMPOUND_DISTRICT_ID] [varchar](255) NULL,
	[ESTIMATED_DELAYED_DELIVERY_DATE] [date] NULL,
	[ESTIMATED_DELIVERY_DATE] [date] NULL,
	[ESTIMATED_DELIVERY_TIME_FROM] [datetime2](7) NULL,
	[ESTIMATED_DELIVERY_TIME_TO] [datetime2](7) NULL,
	[ESTIMATED_DELIVERY_DATE_PROBABILITY] [float] NULL,
	[IS_RELEVANT_FOR_PRODUCTION_FLAG] [int] NULL,
	[LAST_MILE_DELIVERY_DATA_CHANGED_FLAG] [int] NULL,
	[ROUTE_RELEVANT_FOR_START_NODE_FLAG] [int] NULL,
	[SHELF_NO_IN_DELIVERY_VEHICLE] [varchar](255) NULL,
	[TARGET_NODE_ROUTING_INFORMATION_TYPE] [varchar](255) NULL,
	[TARGET_NODE_ROUTING_INFORMATION_CODE] [varchar](255) NULL,
	[TARGET_NODE_ZIP_CODE] [varchar](255) NULL,
	[TARGET_NODE_STREET_CODE] [varchar](255) NULL,
	[TARGET_NODE_HOUSE_NUMBER_CODE] [varchar](255) NULL,
	[TARGET_NODE_PRODUCT_CODE_NATIONAL] [varchar](255) NULL,
	[ETC_ID] [bigint] NULL,
	[CORR_CHECK_CODE] [int] NULL,
	[CORR_ERROR_CODE] [int] NULL,
	[CORR_INSTRUCTION_ID] [bigint] NULL,
	[CORR_ORIG_EVENT_ID] [bigint] NULL,
	[CORR_PROTOCOL_VERSION] [int] NULL,
	[CORR_SCRIPT_ID] [bigint] NULL,
	[CORR_TO_BE_ARCHIVED_ORIGINATOR] [varchar](255) NULL,
	[CREATION_LOC_ADDRESS_COUNTRY] [varchar](255) NULL,
	[ENRICHMENT_STATUS] [varchar](255) NULL,
	[ERROR_WEBMETHODS_FUNCTION] [varchar](255) NULL,
	[ERROR_WEBMETHODS_LEVEL] [varchar](255) NULL,
	[ERROR_WEBMETHODS_MESSAGE] [varchar](255) NULL,
	[ERROR_WEBMETHODS_WARNING_CODE] [varchar](255) NULL,
	[DATA_SOURCE_ID] [int] NULL,
	[LINE_NO] [int] NULL,
	[LOAD_ID] [int] NULL,
	[EVENT_CREATION_TS] [datetime2](7) NULL,
	[EVENT_HASHVALUE] [varchar](255) NULL,
	[FORMAT_ADJUST_COMMENT] [varchar](255) NULL,
	[FORMAT_ADJUST_CORRECTION_TS] [datetime2](7) NULL,
	[FORMAT_ADJUST_ORIG_EVENT_ID] [bigint] NULL,
	[FORMAT_ADJUST_ORIG_EVT_PRED_ID] [bigint] NULL,
	[FORMAT_ADJUST_POST_PROC_ADJUST] [int] NULL,
	[FORMAT_ADJUST_REVISER] [varchar](255) NULL,
	[FORMAT_ADJUST_SYNTHETIC_EVENT] [int] NULL,
	[FORMAT_ERROR_CHECK_CODE] [varchar](255) NULL,
	[FORMAT_ERROR_CODE] [varchar](255) NULL,
	[FORMAT_ERROR_TS] [datetime2](7) NULL,
	[PRI_ID_SOLLWEG_TARGET_NODE] [bigint] NULL,
	[LGO_ID] [bigint] NULL,
	[CRT_ID] [bigint] NULL,
	[MHD_ID] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[CANONICAL_TRACK_EVENT_NOTIFICATION_HEADER]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[CANONICAL_TRACK_EVENT_NOTIFICATION_HEADER](
	[NNH_ID] [bigint] NULL,
	[NOTIF_CREATION_TIMESTAMP] [datetime2](7) NULL,
	[NOTIFICATION_ID] [bigint] NULL,
	[NOTIF_MANUALLY_CREATED_FLAG] [int] NULL,
	[NOTIF_TRIGGERING_EVENT_ID] [varchar](255) NULL,
	[CTE_ID] [bigint] NULL,
	[MHD_ID] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[COMPUTED_ROUTE_NODE]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[COMPUTED_ROUTE_NODE](
	[CRN_ID] [bigint] NULL,
	[CTE_ID] [bigint] NULL,
	[EVENT_ID] [varchar](255) NULL,
	[SEQUENCE_NO] [int] NULL,
	[CURRENT_DISTRICT] [varchar](255) NULL,
	[PRODUCTION_LOCATION_NAME] [varchar](255) NULL,
	[PRODUCTION_LOCATION_ROUTING_REGION] [varchar](255) NULL,
	[PRODUCTION_LOCATION_LOCATION] [varchar](255) NULL,
	[PRODUCTION_LOCATION_CODE_NUMBER] [varchar](255) NULL,
	[PRODUCTION_LOCATION_PROCESS_CODE] [varchar](255) NULL,
	[PRODUCTION_FACILITY_TYPE] [varchar](255) NULL,
	[PRODUCTION_FACILITY_VALUE] [varchar](255) NULL,
	[START_NODE_FLAG] [int] NULL,
	[TARGET_NODE_FLAG] [int] NULL,
	[TOUR_AGNR] [varchar](255) NULL,
	[POSITION_IN_TOUR] [varchar](255) NULL,
	[ARRIVAL_TIME_IN_TOUR] [varchar](255) NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[DETAIL_SOURCE_INFORMATION]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[DETAIL_SOURCE_INFORMATION](
	[DSI_ID] [bigint] NULL,
	[CTE_ID] [bigint] NULL,
	[DETAIL_SOURCE_INFORMATION_TYPE] [varchar](255) NULL,
	[DETAIL_SOURCE_INFORMATION_VALUE] [varchar](255) NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[IDENTIFIER]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[IDENTIFIER](
	[IDC_ID] [bigint] NULL,
	[IDENTIFIER_TYPE] [varchar](255) NULL,
	[IDENTIFIER_VALUE] [varchar](255) NULL,
	[IDENTIFIER_STATUS] [varchar](255) NULL,
	[MAIN_IDENTIFIER_FLAG] [int] NULL,
	[SHIPMENT_IDENTIFIER_FLAG] [int] NULL,
	[IDC_ID_CONTAINER] [bigint] NULL,
	[IDT_ID] [bigint] NULL,
	[CTE_ID] [bigint] NULL,
	[IDC_ID_FOLLOWER] [bigint] NULL,
	[LOI_ID] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[MESSAGE_HEADER]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[MESSAGE_HEADER](
	[MHD_ID] [bigint] NULL,
	[MSG_HDR] [varchar](max) NULL,
	[MSG_HDR_CREATION_TS] [datetime2](7) NULL,
	[MSG_HDR_DEVICE_ID] [varchar](255) NULL,
	[MSG_HDR_DEVICE_NAME] [varchar](255) NULL,
	[MSG_HDR_DEVICE_TYPE] [varchar](255) NULL,
	[MSG_HDR_DS_DSTID] [int] NULL,
	[MSG_HDR_DS_NAME] [varchar](255) NULL,
	[MSG_HDR_DS_RECEIVING_TS] [datetime2](7) NULL,
	[MSG_HDR_DS_VERSION] [varchar](255) NULL,
	[MSG_HDR_EXPORT_FILE] [varchar](255) NULL,
	[MSG_HDR_ID] [varchar](255) NULL,
	[MSG_HDR_ID_TYPE] [varchar](255) NULL,
	[MSG_HDR_IS_TEST] [varchar](255) NULL,
	[MSG_HDR_MSG_FORMAT_TYPE] [varchar](255) NULL,
	[MSG_HDR_MSG_FORMAT_VER] [varchar](255) NULL,
	[MSG_HDR_PROCESSINGTS_NAME1] [varchar](255) NULL,
	[MSG_HDR_PROCESSINGTS_NAME2] [varchar](255) NULL,
	[MSG_HDR_PROCESSING_TS_1] [datetime2](7) NULL,
	[MSG_HDR_PROCESSING_TS_2] [datetime2](7) NULL,
	[MSG_HDR_PROCESS_DESC] [varchar](255) NULL,
	[MSG_HDR_RECIPIENT] [varchar](255) NULL,
	[MSG_HDR_SENDER] [varchar](255) NULL,
	[MSG_HDR_SW_NAME] [varchar](255) NULL,
	[MSG_HDR_SW_TYPE] [varchar](255) NULL,
	[MSG_HDR_SW_VERSION] [varchar](255) NULL,
	[MHD_ID_TRIGGERING] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[NOTIFICATION_TYPE]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[NOTIFICATION_TYPE](
	[NNT_ID] [bigint] NULL,
	[NOTIF_ALREADY_SENT_FLAG] [int] NULL,
	[NOTIF_TRG_STATE_CHANGE_SYNTH_FLAG] [int] NULL,
	[NOTIF_TYPE_NAME] [varchar](255) NULL,
	[NNH_ID] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD](
	[ADD_SERVICES_ORDER_TYPE] [varchar](255) NULL,
	[COUNTRIES_COUNTRY_CODE] [varchar](255) NULL,
	[DELIVERY_NET] [varchar](255) NULL,
	[DTM_TOUR_ID] [bigint] NULL,
	[DTM_TOUR_POSITION_ID] [bigint] NULL,
	[ESTIMATED_DELAYED_DELIVERY_DT] [date] NULL,
	[ESTIMATED_DELIVERY_DT_PROBABILITY] [float] NULL,
	[GENERAL_LIVE_TRACKING_AVAILABILITY_FLAG] [int] NULL,
	[INDUCTION_BAN_FLAG] [int] NULL,
	[LAST_COMPUTED_ROUTE_RECEIPT_ID] [bigint] NULL,
	[PARENT_CONTAINER_INFO_CONTAINER_TYPE] [varchar](255) NULL,
	[PARENT_CONTAINER_INFO_IDENTIFIER] [varchar](255) NULL,
	[PARENT_CONTAINER_INFO_IDENTIFIER_LP_DATA_SOURCE] [varchar](255) NULL,
	[PARENT_CONTAINER_INFO_IDENTIFIER_TYPE] [varchar](255) NULL,
	[PARENT_CONTAINER_INFO_PSLZ_ID] [int] NULL,
	[PARENT_CONTAINER_INFO_SOURCE_EVENT_ID] [bigint] NULL,
	[PARENT_CONTAINER_INFO_TS] [datetime2](7) NULL,
	[PLAN_DELIVERY_FROM_TS] [datetime2](7) NULL,
	[PLAN_DELIVERY_TO_TS] [datetime2](7) NULL,
	[POSITION_IN_SHIPMENT] [int] NULL,
	[PSLZ_CLOSED_FLAG] [int] NULL,
	[PSLZ_CREATION_TS] [datetime2](7) NULL,
	[PSLZ_DISCHARGE_FLAG] [int] NULL,
	[PSLZ_FORCED_CLOSURE_FLAG] [int] NULL,
	[PSLZ_ID] [bigint] NULL,
	[PSLZ_LAST_UPDATE_TS] [datetime2](7) NULL,
	[PSLZ_QUALITY_IND] [varchar](255) NULL,
	[PSLZ_VERSION_NUMBER] [int] NULL,
	[SOURCE_COUNTRY_CODE] [varchar](255) NULL,
	[SPECIFIED_HEIGHT] [float] NULL,
	[SPECIFIED_HEIGHT_UNIT] [varchar](255) NULL,
	[SPECIFIED_LENGTH] [float] NULL,
	[SPECIFIED_LENGTH_UNIT] [varchar](255) NULL,
	[SPECIFIED_VOLUME] [float] NULL,
	[SPECIFIED_VOLUME_UNIT] [varchar](255) NULL,
	[SPECIFIED_WEIGHT] [float] NULL,
	[SPECIFIED_WEIGHT_UNIT] [varchar](255) NULL,
	[SPECIFIED_WIDTH] [float] NULL,
	[SPECIFIED_WIDTH_UNIT] [varchar](255) NULL,
	[STATE_M_LOGISTIC_LASTCHANGE_TS] [datetime2](7) NULL,
	[STATE_M_LOGISTIC_STATE] [varchar](255) NULL,
	[STATE_M_PAN_DATA_LASTCHANGE_TS] [datetime2](7) NULL,
	[STATE_M_PAN_DATA_STATE] [varchar](255) NULL,
	[STATE_M_TGT_PATH_LASTCHANGE_TS] [datetime2](7) NULL,
	[STATE_M_TGT_PATH_STATE] [varchar](255) NULL,
	[TOUR_VALID_DATE] [date] NULL,
	[EKP] [float] NULL,
	[METHOD_CODE] [varchar](255) NULL,
	[OBLIGATION_TO_TRACK] [int] NULL,
	[ORDER_NUMBER] [varchar](255) NULL,
	[ORDER_POSITION] [int] NULL,
	[PARTICIPATION] [varchar](255) NULL,
	[PRODUCT_CODE] [varchar](255) NULL,
	[PRODUCT_KEY] [varchar](255) NULL,
	[PRODUCT_TYPE] [varchar](255) NULL,
	[SHIP_FUNCT_STATE] [varchar](255) NULL,
	[SHIP_ID] [bigint] NULL,
	[TOTAL_PACKAGE_NUMBER] [int] NULL,
	[SUCCESSOR_TIMESTAMP] [datetime2](7) NULL,
	[SUCCESSOR_PSLZ_ID] [bigint] NULL,
	[SUCCESSOR_REASON] [varchar](255) NULL,
	[PREDECESSOR_TIMESTAMP] [datetime2](7) NULL,
	[PREDECESSOR_PSLZ_ID] [bigint] NULL,
	[PREDECESSOR_REASON] [varchar](255) NULL,
	[ACTUAL_WEIGHT] [float] NULL,
	[ACTUAL_WEIGHT_UNIT] [varchar](255) NULL,
	[ACTUAL_WIDTH] [float] NULL,
	[ACTUAL_WIDTH_UNIT] [varchar](255) NULL,
	[ACTUAL_HEIGHT] [float] NULL,
	[ACTUAL_HEIGHT_UNIT] [varchar](255) NULL,
	[ACTUAL_LENGTH] [float] NULL,
	[ACTUAL_LENGTH_UNIT] [varchar](255) NULL,
	[ACTUAL_VOLUME] [float] NULL,
	[ACTUAL_VOLUME_UNIT] [varchar](255) NULL,
	[ADDITIONAL_SERIVCES_ORDER_TYPE] [varchar](255) NULL,
	[ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[NNH_ID] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_PARTNER_INFORMATION]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_PARTNER_INFORMATION](
	[BCP_ID] [bigint] NULL,
	[PARTNER_ROLE] [varchar](255) NULL,
	[POST_NUMBER] [int] NULL,
	[FIRST_NAME] [varchar](255) NULL,
	[NAME] [varchar](255) NULL,
	[NAMING_AFFIX] [varchar](255) NULL,
	[CONTACT_OPPORTUNITY] [varchar](max) NULL,
	[PARTNER_ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[LOCATION_ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[ADDRESS_TYPE] [varchar](255) NULL,
	[ADDRESS_ADDITION] [varchar](255) NULL,
	[STREET] [varchar](255) NULL,
	[HOUSE_NUMBER] [varchar](255) NULL,
	[HOUSE_NUMBER_ADDITION] [varchar](255) NULL,
	[POST_OFFICE_BOX] [varchar](255) NULL,
	[ZIP] [varchar](255) NULL,
	[CITY] [varchar](255) NULL,
	[STATE_CODE] [varchar](255) NULL,
	[COUNTRY_CODE] [varchar](255) NULL,
	[EMAIL] [varchar](255) NULL,
	[SMS] [varchar](255) NULL,
	[CUSTOMER_IDENTIFICATION_STATUS] [varchar](255) NULL,
	[ADDRESSED_DELIVERY_CHANNEL] [varchar](255) NULL,
	[NNH_ID] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_ROUTING_INFORMATION]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_ROUTING_INFORMATION](
	[BCR_ID] [bigint] NULL,
	[BCP_ID] [bigint] NULL,
	[ROUTING_INFORMATION_TYPE] [varchar](255) NULL,
	[ROUTING_INFORMATION_CODE] [varchar](255) NULL,
	[COUNTRY_CODE] [varchar](255) NULL,
	[ZIP_CODE] [varchar](255) NULL,
	[HOUSE_NUMBER_CODE] [varchar](255) NULL,
	[STREET_CODE] [varchar](255) NULL,
	[PRODUCT_CODE_NATIONAL] [varchar](255) NULL,
	[PRODUCT_CODE_INTERNATIONAL] [varchar](255) NULL,
	[FEATURE_CODE_INTERNATIONAL] [varchar](255) NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_VALUE_ADDED_SERVICE]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_VALUE_ADDED_SERVICE](
	[BCS_ID] [bigint] NULL,
	[SERVICE_ABBREVIATION] [varchar](255) NULL,
	[SERVICE_SOURCE_DSTID] [smallint] NULL,
	[SERVICE_SOURCE_ODS_EVENT_ID] [bigint] NULL,
	[SERVICE_STATUS] [varchar](255) NULL,
	[NNH_ID] [bigint] NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PARTNER_INFORMATION]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PARTNER_INFORMATION](
	[PIN_ID] [bigint] NULL,
	[CTE_ID] [bigint] NULL,
	[SHIPMENT_PARTNER_INFORMATION_FLAG] [int] NULL,
	[CONTACT_PERSON] [varchar](255) NULL,
	[ADDTIONAL_CONTACT_PERSON] [varchar](max) NULL,
	[ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[DISTRIBUTION_CODE] [varchar](255) NULL,
	[EKP] [nchar](1) NULL,
	[EMPLOYEE_ID] [varchar](255) NULL,
	[POST_NUMBER] [int] NULL,
	[SALUTATION] [varchar](255) NULL,
	[TITLE] [varchar](255) NULL,
	[FIRST_NAME] [varchar](255) NULL,
	[NAME] [varchar](255) NULL,
	[NAMING_AFFIX] [varchar](255) NULL,
	[PARTNER_TYPE] [varchar](255) NULL,
	[PARTNER_CLASSIFICATION] [varchar](255) NULL,
	[CLIENT_ACCOUNT_NUMBER] [varchar](255) NULL,
	[DATE_OF_BIRTH] [date] NULL,
	[PLACE_OF_BIRTH] [varchar](255) NULL,
	[NATIONALITY] [varchar](255) NULL,
	[ORGANISATION_ID] [varchar](255) NULL,
	[VAT_ID] [varchar](255) NULL,
	[CONTACT_OPPORTUNITY] [varchar](max) NULL,
	[PARTNER_ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[LOCATION_ADDITIONAL_INFORMATION] [varchar](max) NULL,
	[LOCATION_ID] [varchar](255) NULL,
	[LARGE_CUSTOMER_ZIP] [varchar](255) NULL,
	[SERVICE_DISTRICT_TYPE] [varchar](255) NULL,
	[SERVICE_DISTRICT_VALUE] [varchar](255) NULL,
	[PRODUCTION_LOCATION_CODE] [varchar](255) NULL,
	[PRODUCTION_LOCATION_ROUTING_REGION] [varchar](255) NULL,
	[PRODUCTION_LOCATION_LOCATION] [varchar](255) NULL,
	[PRODUCTION_LOCATION_CODE_NUMBER] [varchar](255) NULL,
	[PRODUCTION_LOCATION_PROCESS_CODE] [varchar](255) NULL,
	[GPS_LONGITUDE] [float] NULL,
	[GPS_LATITUDE] [float] NULL,
	[ADDRESS_TYPE] [varchar](255) NULL,
	[ADDRESS_ADDITION] [varchar](255) NULL,
	[STREET] [varchar](255) NULL,
	[HOUSE_NUMBER] [varchar](255) NULL,
	[HOUSE_NUMBER_ADDITION] [varchar](255) NULL,
	[POST_OFFICE_BOX] [varchar](255) NULL,
	[ZIP] [varchar](255) NULL,
	[CITY] [varchar](255) NULL,
	[DISTRICT] [varchar](255) NULL,
	[STATE_CODE] [varchar](255) NULL,
	[COUNTRY_CODE] [varchar](255) NULL,
	[EMAIL] [varchar](255) NULL,
	[SMS] [varchar](255) NULL,
	[NAD_ID] [bigint] NULL,
	[NAE_ID] [bigint] NULL,
	[PARTNER_ROLE] [varchar](255) NULL,
	[PRI_ID] [bigint] NULL,
	[PRODUCTION_FACILITY_RIO_ID] [bigint] NULL,
	[PRODUCTION_FACILITY_NUMBER_TYPE] [varchar](255) NULL,
	[PRODUCTION_FACILITY_NUMBER_VALUE] [varchar](255) NULL,
	[PRODUCTION_FACILITY_NUMBER_STATUS] [varchar](255) NULL,
	[PRODUCTION_FACILITY_DESCRIPTION] [varchar](255) NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PARTNER_ROUTING_INFORMATION]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PARTNER_ROUTING_INFORMATION](
	[PRI_ID] [bigint] NULL,
	[PIN_ID] [bigint] NULL,
	[ROUTING_INFORMATION_TYPE] [varchar](255) NULL,
	[ROUTING_INFORMATION_CODE] [varchar](255) NULL,
	[COUNTRY_CODE] [varchar](255) NULL,
	[ZIP_CODE] [varchar](255) NULL,
	[HOUSE_NUMBER_CODE] [varchar](255) NULL,
	[STREET_CODE] [varchar](255) NULL,
	[PRODUCT_CODE_NATIONAL] [varchar](255) NULL,
	[PRODUCT_CODE_INTERNATIONAL] [varchar](255) NULL,
	[FEATURE_CODE_INTERNATIONAL] [varchar](255) NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PLAIN_XML]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PLAIN_XML](
	[XMLSTRING] [varchar](max) NULL,
	[CREATED_TS] [timestamp] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[PLAIN_XML1]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[PLAIN_XML1](
	[XMLSTRING] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [PICKUP_TO_DELIVERY].[SOLLWEG_EDGE]    Script Date: 28.04.2022 14:54:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PICKUP_TO_DELIVERY].[SOLLWEG_EDGE](
	[SWE_ID] [bigint] NULL,
	[CRN_ID_NODE] [bigint] NULL,
	[CRN_ID_NEXT_NODE] [bigint] NULL,
	[EDGE_ID] [varchar](255) NULL,
	[SEQUENCE_NO] [int] NULL,
	[NODE_CUT_OFF_DTM] [datetime2](7) NULL,
	[NODE_CUT_OFF_TIME] [time](7) NULL,
	[PRODUCT_CODE] [varchar](255) NULL,
	[TRANSPORTATION_DURATION] [int] NULL,
	[NEXT_NODE_DISPOSITIVE_DTM] [datetime2](7) NULL,
	[DateCreated] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[ADDITIONAL_STATUS_CODES] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[CANONICAL_TRACK_EVENT] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[CANONICAL_TRACK_EVENT_NOTIFICATION_HEADER] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[COMPUTED_ROUTE_NODE] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[DETAIL_SOURCE_INFORMATION] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[IDENTIFIER] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[MESSAGE_HEADER] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[NOTIFICATION_TYPE] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_PARTNER_INFORMATION] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_ROUTING_INFORMATION] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[PACKAGE_BATCH_CARD_VALUE_ADDED_SERVICE] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[PARTNER_INFORMATION] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[PARTNER_ROUTING_INFORMATION] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [PICKUP_TO_DELIVERY].[SOLLWEG_EDGE] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO



